apiVersion: v1
kind: Pod
metadata:
  name: collapsed-pod
spec:
  restartPolicy: OnFailure  # This prevents immediate restarts
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
